connectors/bitbucket-server/src/main/java/com/vmware/connectors/bitbucket/server/BitbucketServerController.java
connectors/bitbucket-server/src/test/java/com/vmware/connectors/bitbucket/server/BitbucketServerControllerTest.java
connectors/jira/src/main/java/com/vmware/connectors/jira/JiraController.java
connectors/jira/src/test/java/com/vmware/connectors/jira/JiraControllerTests.java

* Uses myself endpoint for Jira test-auth
* Uses pull-request-suggestions endpoint for Bitbucket Server test-auth

APF-776: Use better urls for test-auth

---

common/connectors-test/src/main/java/com/vmware/connectors/test/ControllerTestsBase.java
connectors/jira/src/main/resources/static/discovery/metadata.hal
connectors/jira/src/test/java/com/vmware/connectors/jira/JiraControllerTests.java
connectors/jira/src/test/resources/regex/email.txt

* Adds unit tests to prove the false positives we were seeing will go away
* Adds a non-word char (outside the group) to prevent many false positives

APF-777: Reduce Jira false positives

---

connectors/salesforce/README.md

APF-802: Update Salesforce README

---

common/connectors-config/src/main/java/com/vmware/connectors/common/web/ConnectorRootController.java

APF-762: Make root discovery cache configurable

---

connectors/bitbucket-server/src/main/java/com/vmware/connectors/bitbucket/server/BitbucketServerController.java
connectors/bitbucket-server/src/test/resources/bitbucket/responses/success.json

APF-804: Fix Bitbucket Server actions

---

connectors/salesforce/README.md

Update Salesforce README

---

common/core/src/main/java/com/vmware/connectors/common/payloads/response/CardAction.java
common/core/src/test/resources/simple.json

APF-807: Add primary flag to action builder

---

common/core/src/main/java/com/vmware/connectors/common/payloads/response/CardBody.java
connectors/salesforce/src/main/java/com/vmware/connectors/salesforce/SalesforceController.java
connectors/salesforce/src/test/java/com/vmware/connectors/salesforce/SalesforceControllerTests.java
connectors/salesforce/src/test/resources/connector/responses/successWithoutPhoneAndRole.json
connectors/salesforce/src/test/resources/salesforce/response/successContactWithoutPhone.json
connectors/salesforce/src/test/resources/salesforce/response/successWithoutRole.json

APF-809: Do not send fields for blank salesforce data

---

connectors/servicenow/src/main/java/com/vmware/connectors/servicenow/ServiceNowController.java
connectors/servicenow/src/test/resources/servicenow/responses/success/cards/card.json
connectors/servicenow/src/test/resources/servicenow/responses/success/cards/card_xx.json

APF-808: Make ServiceNow Approve a primary action

---

connectors/jira/src/main/java/com/vmware/connectors/jira/JiraController.java
connectors/jira/src/main/resources/cards/text.properties
connectors/jira/src/test/resources/cards/text_xx.properties
connectors/jira/src/test/resources/connector/responses/APF-27.json
connectors/jira/src/test/resources/connector/responses/success.json
connectors/jira/src/test/resources/connector/responses/success_xx.json
connectors/jira/src/test/resources/jira/responses/APF-27.json

Per business & UX feedback:
* Makes card title the ticket's summary
* Makes card subtitle the ticket's id (ABC-123)
* Adds a non-ellipsized summary field
* Filters away empty fields
* Adds priority field
* Adds resolution field
* Adds fix versions field
* Removes reporter field
* Removes labels field
* Removes description field
Also:
* Adds ability to localize "Comment" user input label
* Changes xx locale unit test to use uppercase instead of foreign language

APF-811: Improve Jira card UX

---

connectors/airwatch/src/test/java/com/vmware/connectors/airwatch/AirWatchControllerTest.java
connectors/airwatch/src/test/resources/regex/email.txt
connectors/concur/src/test/java/com/vmware/connectors/concur/ConcurControllerTest.java
connectors/salesforce/src/test/java/com/vmware/connectors/salesforce/SalesforceControllerTest.java
connectors/salesforce/src/test/resources/regex/email.txt
connectors/servicenow/src/test/java/com/vmware/connectors/servicenow/ServiceNowControllerTest.java
connectors/servicenow/src/test/resources/regex/email.txt

APF-972: Improve connector regex unit tests

---

common/connectors-config/src/main/java/com/vmware/connectors/common/utils/CommonUtils.java
connectors/aws-cert/src/main/java/com/vmware/connectors/aws/cert/AwsCertController.java
connectors/bitbucket-server/src/main/java/com/vmware/connectors/bitbucket/server/BitbucketServerController.java
connectors/concur/src/main/java/com/vmware/connectors/concur/ConcurController.java
connectors/github-pr/src/main/java/com/vmware/connectors/github/pr/GithubPrController.java
connectors/gitlab-pr/src/main/java/com/vmware/connectors/gitlab/pr/GitlabPrController.java
connectors/jira/src/main/java/com/vmware/connectors/jira/JiraController.java
connectors/salesforce/src/main/java/com/vmware/connectors/salesforce/SalesforceController.java
connectors/salesforce/src/test/java/com/vmware/connectors/salesforce/SalesforceControllerTest.java
connectors/servicenow/src/main/java/com/vmware/connectors/servicenow/ServiceNowController.java

* Cleaned up method signature pollution of HttpRequest vs. HttpServletRequest
* Fixed a few warnings that I noticed
* Fixed a few whitespace misalignments that I noticed

APF-895: Cleanup

---

common/core/src/main/java/com/vmware/connectors/common/utils/Reactive.java
connectors/airwatch/src/main/java/com/vmware/connectors/airwatch/AirWatchController.java
connectors/aws-cert/src/main/java/com/vmware/connectors/aws/cert/AwsCertController.java
connectors/bitbucket-server/src/main/java/com/vmware/connectors/bitbucket/server/BitbucketServerController.java
connectors/concur/src/main/java/com/vmware/connectors/concur/ConcurController.java
connectors/github-pr/src/main/java/com/vmware/connectors/github/pr/GithubPrController.java
connectors/gitlab-pr/src/main/java/com/vmware/connectors/gitlab/pr/GitlabPrController.java
connectors/jira/src/main/java/com/vmware/connectors/jira/JiraController.java
connectors/salesforce/src/main/java/com/vmware/connectors/salesforce/SalesforceController.java
connectors/servicenow/src/main/java/com/vmware/connectors/servicenow/ServiceNowController.java

Used Mono where possible and got rid of
Reactive.toResponseEntity

APF-957 Tidy up reactive stuff

---

connectors/airwatch/pom.xml
connectors/aws-cert/pom.xml
connectors/bitbucket-server/pom.xml
connectors/concur/pom.xml
connectors/github-pr/pom.xml
connectors/gitlab-pr/pom.xml
connectors/jira/pom.xml
connectors/pom.xml
connectors/salesforce/pom.xml
connectors/servicenow/pom.xml
pom.xml

Put Docker-based test stuff into separate profile so it doesn't clash with real Docker.
Make Docker push conditional on branch being master.
Bamboo isn't pushing images yet. See APF-1071.

APF-997 Prepare Docker stuff for Bamboo

---

README.md
TROUBLESHOOTING.md
connectors/airwatch/README.md
connectors/airwatch/src/main/service/rhel/files/default-conf/start.sh
connectors/aws-cert/src/main/service/rhel/files/default-conf/start.sh
connectors/bitbucket-server/src/main/service/rhel/files/default-conf/start.sh
connectors/concur/src/main/service/rhel/files/default-conf/start.sh
connectors/github-pr/src/main/service/rhel/files/default-conf/start.sh
connectors/gitlab-pr/src/main/service/rhel/files/default-conf/start.sh
connectors/jira/src/main/service/rhel/files/default-conf/start.sh
connectors/pom.xml
connectors/salesforce/src/main/service/rhel/files/default-conf/start.sh
connectors/servicenow/src/main/service/rhel/files/default-conf/start.sh

* Updates README.md with various ways to build and run a connector
* Adds a TROUBLESHOOTING.md with common errors
* Updates RPMs to specify -server in their java command
* Removes unused prod profile in the docker container entry points

APF-1042: Update README

---

connectors/airwatch/src/test/java/com/vmware/connectors/airwatch/AirWatchControllerTest.java

It was incorrectly expecting a call for the second bundle ID
even after the first one had returned 500. This is not guaranteed
to happen.

APF-1021 Fix testRequestCardsOneServerError in AW

---

connectors/salesforce/src/main/java/com/vmware/connectors/salesforce/SalesforceController.java

This allows us to avoid creating a Mono that emits a list,
which feels awkward.

APF-1154 Use Flux instead of List

---

connectors/salesforce/src/main/java/com/vmware/connectors/salesforce/SalesforceController.java
connectors/salesforce/src/main/resources/application.yml
connectors/salesforce/src/main/resources/cards/text.properties
connectors/salesforce/src/test/resources/cards/text_xx.properties
connectors/salesforce/src/test/resources/connector/responses/successCardsForSender.json
connectors/salesforce/src/test/resources/connector/responses/successCardsForSender_xx.json

Added Card actions for updating the "Next Steps" and "Close Date".
Tested the functionality end-end. Added the screenshot below:

Apf 1156 add card actions for salesforce connector

---

connectors/airwatch/README.md

https://github.com/vmware/connectors-workspace-one/tree/APF-1172-Update-aw-conn-readme/connectors/airwatch#airwatch-connector

APF-1172 App discovery ReadMe update

---

connectors/salesforce/src/main/resources/application.yml
connectors/salesforce/src/test/java/com/vmware/connectors/salesforce/SalesforceControllerTest.java

Upgraded all the API's to v39.0. Tested all the v39.0 API's functionalities.

APF-1159-Upgrade all APIs to v39.0

---

connectors/bitbucket-server/src/main/java/com/vmware/connectors/bitbucket/server/BitbucketServerController.java
connectors/bitbucket-server/src/test/resources/bitbucket/responses/success.json
connectors/bitbucket-server/src/test/resources/bitbucket/responses/success_xx.json
connectors/github-pr/src/main/java/com/vmware/connectors/github/pr/GithubPrController.java
connectors/github-pr/src/test/resources/responses/success/cards/card.json
connectors/github-pr/src/test/resources/responses/success/cards/card_xx.json
connectors/gitlab-pr/src/main/java/com/vmware/connectors/gitlab/pr/GitlabPrController.java
connectors/gitlab-pr/src/test/resources/responses/success/cards/card.json
connectors/gitlab-pr/src/test/resources/responses/success/cards/card_xx.json

* Changes Bitbucket Server PR comments to be multiline
* Changes Github PR comments to be multiline
* Changes Gitlab PR comments to be multiline
* Updates unit tests

APF-1382: Make PR comments multiline

---

connectors/bitbucket-server/src/test/java/com/vmware/connectors/bitbucket/server/BitbucketServerControllerTest.java
connectors/concur/README.md
connectors/concur/src/main/java/com/vmware/connectors/concur/ConcurController.java
connectors/concur/src/main/resources/application.yml
connectors/concur/src/main/service/rhel/files/default-conf/application.properties
connectors/concur/src/test/java/com/vmware/connectors/concur/ConcurControllerTest.java
connectors/concur/src/test/resources/application.properties
connectors/concur/src/test/resources/concur/responses/oauth_token.json

There were some issues with ngrok today. So I was not able to test it in boxer client. I am trying to see to test it with the alternatives to ngrok.

Apf 838 add support for password grant in concur connector

---

common/connectors-test/pom.xml
common/core-test/pom.xml
pom.xml

* Updates jjwt from 0.9.0 to 0.10.1

APF-1403: Update jjwt

---

connectors/concur/src/main/java/com/vmware/connectors/concur/ConcurController.java
connectors/concur/src/test/java/com/vmware/connectors/concur/ConcurControllerTest.java

* Fixes 403 vs. 401 problem in Concur authorization check
* Updates unit test

APF-1399: Fix Concur authorization

---

common/connectors-test/src/main/java/com/vmware/connectors/test/ControllerTestsBase.java
connectors/airwatch/src/main/resources/static/discovery/metadata.json
connectors/airwatch/src/test/resources/connector/responses/metadata.json
connectors/aws-cert/src/main/resources/static/discovery/metadata.json
connectors/aws-cert/src/test/resources/discovery/metadata.json
connectors/bitbucket-server/src/main/resources/static/discovery/metadata.json
connectors/concur/src/main/resources/static/discovery/metadata.json
connectors/github-pr/src/main/resources/static/discovery/metadata.json
connectors/gitlab-pr/src/main/resources/static/discovery/metadata.json
connectors/jira/src/main/resources/static/discovery/metadata.json
connectors/salesforce/src/main/resources/static/discovery/metadata.json
connectors/servicenow/src/main/resources/static/discovery/metadata.json

* Changes object_types from array of objects to object / Map
* Updates tests

APF-1523: Change object_types to object

---

connectors/concur/src/main/java/com/vmware/connectors/concur/ConcurController.java

* Adds additional logging to the Concur connector
* Fixes minor indention discrepancies

APF-1528: Add more logging to concur connector

---

common/core/src/main/java/com/vmware/connectors/common/utils/AuthUtil.java
connectors/hub-servicenow/src/main/java/com/vmware/connectors/hub/servicenow/HubServiceNowController.java

APF-1230: Tweaks for testing

---

connectors/hub-concur/src/main/java/com/vmware/connectors/concur/service/HubConcurService.java
connectors/hub-concur/src/test/resources/application-test.properties

* Changes the hardcoded user to be configurable for demo purposes
* Adds todo comments w/ tickets for the pending work related to user

APF-1714: Temp make user config for demo
